### PR TITLE
RUN-5454 window.getOptions does not return contentNavigation info

### PR DESCRIPTION
**Pull request by aziz512**
#### Description of Change
Fixes the bug where `contentNavigation` option passed to a window is properly never consumed or used.

#### Checklist
- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] PR title starts with the JIRA ticket [pull request process](https://github.com/openfin/Internal-Wiki/wiki/Pull-Request-Process)
- [x] PR release notes describe the change in a way relevant to app-developers
- [x] Link to new tests added
- [x] PR has assigned reviewers

#### Release Notes
Notes: Fixed `contentNavigation` option never being consumed

@MichaelMCoates  @rdepena @datamadic  @luiemilio

### CODE REVIEW

**Comment by whyn07m3** [comment]
5 days ago, there was probably a problem with test runner migration. Aziz will kick off testing again, in a few

**Comment by datamadic** [comment]
@aziz512 are the fails relevant here?

**Comment by aziz512** [comment]
> @aziz512 are the fails relevant here?

Looks like they are. Will investigate

**Comment by aziz512** [comment]
With the last commit I enabled checking contentNavigation rules of both Windows and Applications.
The change also completes the TODO about switching to webcontents.loadURL()

**Comment by datamadic** [comment]
Are the fails relevant again here? https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5d574e425cca4e5a7198d22d

Also, conflicts.

**Comment by aziz512** [comment]
Testing contentNavigation property on Windows:
https://testing-dashboard.openfin.co/#/app/tests/5d6991de5cca4e5a7198d379/edit
https://testing-dashboard.openfin.co/#/app/tests/5d6991a75cca4e5a7198d378/edit

**Comment by datamadic** [comment]
is this fail expected?https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5d6ec7555cca4e5a7198d389

**Comment by aziz512** [comment]
> is this fail expected?https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5d6ec7555cca4e5a7198d389

@datamadic  Yes, using webcontents' `webContents.loadURL(url);` method changed the error to a more standard -300 error instead of the custom one we had.

**Comment by aziz512** [comment]
I don't seem to have the access to update that test, but to accommodate for this change we should change the last line to:
`    	.catch(err => completionCallback(err.toString().includes('-300')));`

**Comment by datamadic** [comment]
@aziz512 conflicts popped up

**Comment by rdepena** [comment]
@aziz512 will need to handle conflicts here.

**Comment by aziz512** [comment]
@datamadic @datamadic
Fixed!

**Pull request merged**
