### PR TITLE
RUN-4104: Add ability to mask RVM payloads; do so for application-log

### PR DESCRIPTION
**Pull request by anguslim**
[JIRA](https://appoji.jira.com/browse/RUN-4104)

Also, if the payload is to be masked, it's not written to the log.

[Runtime PR](https://github.com/openfin/runtime/pull/996)

[Test results](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5afb140f4ecc2a37d5a48677)

### CODE REVIEW

**Comment by anguslim** [comment]
No particular reason; I just thought it was too specific for the generic `RvmMsgBase` object. Do we expect to suppress logs for messages in the future (in which case it'd make more sense in `RvmMsgBase`)?

**Comment by datamadic** [comment]
Is the RVM using it for something, or is it just used in the core?

**Comment by anguslim** [comment]
It's only used in the core and runtime. The RVM has to receive the actual payload since it's the actual entity writing to disk.

**Comment by anguslim** [comment]
That's true, the field is unnecessarily added to the payload. It's now a separate argument.

**Comment by datamadic** [comment]
@anguslim can you post updated test results? 

@whyn07m3 looks good?

**Comment by whyn07m3** [comment]
@datamadic oh, sorry, don't have rights to review

**Pull request merged**
