### PR TITLE
RUN-3013: Resizeable gets lost on maximize + restore

### PR DESCRIPTION
**Pull request by joneit**
Tested manually.

### CODE REVIEW

**Comment by HarsimranSingh** [comment]
Not sure this accounts for double clicking the top of the window to restore.

Also, the 18 stable release behaves correctly, but something broke between then and now. That needs more investigation.

**Comment by joneit** [comment]
Just noticed I apparently closed this. Didn't mean to!

**Comment by joneit** [comment]
@HarsimranSingh Regarding double-click on title bar:
* Double-clicking to maximize does nothing, as expected when the window is supposed to be non-resizable.
* Double-clicking programmatically maximized window does respond by restoring window to pre-maximized size. **As you suspected, the edge arrows are now active.**

**Comment by joneit** [comment]
@HarsimranSingh Regarding
> something broke between then and now
Hello Openfin using this fix rebased to tip of `develop` & deployed on top of .21.11 is working as expected.... what exactly "broke?"

**Comment by joneit** [comment]
@HarsimranSingh Regarding double-click on title bar:
* Double-clicking to maximize does nothing, as expected when the window is supposed to be non-resizable.
* Double-clicking programmatically maximized window does respond by unmaximizing window (restoring to pre-maximized size) but **as you suspected,** our `restore` function apparently is not being called as the edge arrows are now active.

**Comment by joneit** [comment]
Use cases to demaximize a maximized non-resizable window:
1. calling `fin.desktop.Window.getCurrent().restore()`
2. double-clicking in the title bar

Closing because:
* We determined that both demaximize use cases were previously working in .18.41 _without the additional code contained in this PR)
* We need a runtime-size fix anyway to deal with use case #2, so let's just figure out what changed on the runtime side and fixing that will probably fix both use cases without any additional javascript.

**Pull request closed without merging**
