### PR TITLE
RUN-5380 fixes window grouping regression

### PR DESCRIPTION
**Pull request by whyn07m3**
#### Description of Change
This PR fixes the regression where windows wouldn't join or merge a group in the multi-runtime environment.

#### Checklist
- [x] PR description included and stakeholders cc'd
- [x] automated test [added](https://testing-dashboard.openfin.co/#/app/tests/5d1372a7cb360141a7dfe750/edit)
- [x] PR title starts with the JIRA ticket
- [x] PR release notes describe the change in a way relevant to app-developers

#### Release Notes
N/A

#### Test Results
- [Windows 7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5d136e2bcb360141a7dfe74e) (1 failed test unrelated to this change)
- [Windows 10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5d136e4ccb360141a7dfe74f) (5 failed tests, unrelated to this change)

### CODE REVIEW

**Comment by whyn07m3** [comment]
@rdepena as we discussed before, the automated test created for this regression can be used for other similar scenarios. I only covered here 1 scenario with my test.

**Comment by rdepena** [comment]
🌳 Talked to Roma offline and this requires a few changes

**Comment by whyn07m3** [comment]
Test results:
✅ [Windows 7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5d14b925cb360141a7dfe76c)
✅ [Windows 10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5d14b834cb360141a7dfe76b)

**Comment by rdepena** [comment]
@whyn07m3 Merge group looks like it's still broken.

**Comment by rdepena** [comment]
Ignore that last comment (about merge being broken)

**Comment by whyn07m3** [comment]
> Ignore that last comment (about merge being broken)

I'm confused

**Comment by rdepena** [comment]
Looks good to me!!

**Pull request merged**
