### PR TITLE
RUN-3228 Remove unneeded `mustSucceed` preload script option

### PR DESCRIPTION
**Pull request by joneit**
Regression [**tests**](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/598de08ad2a02971da3a62bf) passed (no relevant fails).

### CODE REVIEW

**Comment by whyn07m3** [comment]
@joneit do you have a test for this case (multiple preload scripts with at least 1 failing, but other getting eval'ed successfully)?

**Comment by joneit** [comment]
No, not for eval error; just for load failure.

**Comment by joneit** [comment]
Per @whyn07m3: Added [new test](https://testing-dashboard.openfin.co/#/app/tests/599ae190d2a02971da3a62f7/edit) for `eval(script)` failure, proving that subsequent scripts in the preload list _are_ `eval`'d even after preceding script fails.

**Comment by joneit** [comment]
Rebased to current `canary` (`8.56.24.3`). (Unfortunately this voids "reviewed" status!)

**Pull request merged**
