### PR TITLE
RUN-3366 writeToLog use toString when avail

### PR DESCRIPTION
**Pull request by joneit**
Please see Jira [RUN-3366](https://appoji.jira.com/browse/RUN-3366) for explanation.

**[Tests](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/59c96bde7cb79f732d10c3ab).**

This is another casual general improvement PR and can slip to next sprint considering this sprint has so much to merge already.

### CODE REVIEW

**Comment by whyn07m3** [comment]
The following is properly being stringified in the `writeToLog` function:

```
log.writeToLog('info', { a: 'lol' });
log.writeToLog('info', ['l', 0, 'l']);
```

What is this PR trying to fix?

**Comment by wenjunche** [comment]
can it skip errorToPOJO and stringify based on verboseLogLevel ?

**Comment by joneit** [comment]
@whyn07m3 please see Jira for answer to your question. when an object has a custom toString, we should use it

**Comment by joneit** [comment]
@wenjunche please elucidate... re `errorToPOJO` we should always do that because some error objects resists stringification otherwise.

**Comment by whyn07m3** [comment]
I haven't come across this use case (Object's custom `.toString`) in our project... Can you please give an example of a real life scenario?..

**Comment by joneit** [comment]
@whyn07m3 `Date` is an example of an object that has its own `toString` which produces something useful (`Sun Oct 01 2017 12:11:11 GMT-0400 (EDT)`). There is no need to stringify.

`JSON.stringify` is not meant for general serialization; it is meant to produce transmittable JSON. Therefore, it is not a completely reliable serializer.

In particular, it will only output representations of the object's own, enumerable properties, ignoring functions and `undefined` values.

Also, objects that implement `toJSON` specifically for data output. `Date` is one such. For example, `Date.toJSON()` produces `"2017-10-01T16:11:11.799Z"` (including the quotes) which is a precise string that all database engines understand (it's also collatable). This value may or may not be suitable for logging. (I didn't go there in this PR.)

Classic use of `toString` for objects is to produce a string representation of the object. `Object.toString` is pretty much useless and _is meant to be overridden._ We've been using `JSON.stringify` because we don't want to log `[Object object]` (produced by `Object.toString`). Fair enough. But when `toString` is overridden, we should use the override. 

This PR simply checks if the object implements `toString` and uses it when it does, before resorting to `JSON.stringify`.

**Comment by whyn07m3** [comment]
@joneit Thank you for providing the use case and explaining! 👍

**Comment by joneit** [comment]
Now prepends class name (when known*) to object stringification:
```
[10/03/17 10:46:36]-[INFO:atom_api_app.cc(1034)] 10/03 10:46:36.118 - MyClass: {"a":17}
```
[**Retested**](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/59d3a2d07cb79f732d10c428).
\___________
\* when object has a `constructor` property and `constructor.name` is neither `'Object'` (plain object; not a class) nor `'Function'` (is a class but anonymous).

**Comment by joneit** [comment]
@HarsimranSingh Added unit tests.

**Pull request merged**
