### PR TITLE
RUN-4075 Set tray icon offline

### PR DESCRIPTION
**Pull request by licui3936**
This PR is to fix the issue in setTrayIcon when running as offline mode.

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] PR title starts with the JIRA ticket [pull request process](https://github.com/openfin/Internal-Wiki/wiki/Pull-Request-Process)
- [x] PR release notes describe the change in a way relevant to app-developers
- [x] PR has assigned reviewers

### CODE REVIEW

**Comment by MichaelMCoates** [comment]
Gotta settle a merge conflict, btw.

**Comment by licui3936** [comment]
resolved conflicts

**Comment by licui3936** [comment]
@pbaize  yeah, will not re-download icon when using offline access unless the icon file doesn't exist in cache.

**Comment by licui3936** [comment]
This one is not needed . will create another one.

**Pull request closed without merging**
