### PR TITLE
RUN-3279 check duplicate uuid if manifestUrl is different

### PR DESCRIPTION
**Pull request by weiteho**
Show error popup only if manifest URL is different from the existing Running instance.

### CODE REVIEW

**Comment by wenjunche** [comment]
missing test links

**Comment by weiteho** [comment]
:white_check_mark: Test Results
* [Windows 7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/59c11c637cb79f732d10c366)
* [Windows 10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/59c11ce47cb79f732d10c367)

**Comment by wenjunche** [comment]
👍

**Comment by rdepena** [comment]
👍

**Comment by HarsimranSingh** [comment]
Need tests

**Pull request merged**
