### PR TITLE
RUN-3049 Extend drag area for frameless window

### PR DESCRIPTION
**Pull request by TomaszMa**
The default drag are really small I extended it to 4 pixels and 6 pixels on corners.

### CODE REVIEW

**Comment by joneit** [comment]
It's about time. :) Framed windows seem to have a **7-pixel** edge grab region. I don't know if 7 is a Windows standard, but it _is_ very comfortable. (The fact that the content area is rendered _inside_ the region instead of superimposed on top of it notwithstanding.) Should we consider 7 for frameless as well?

**Comment by rdepena** [comment]
👍

**Comment by HarsimranSingh** [comment]
If this change is happening, we need to update the docs

**Comment by TomaszMa** [comment]
Doc update: https://github.com/openfin/javascript-adapter/pull/342

**Comment by datamadic** [comment]
In addition, ideally this is accompanied with a test in our automated testing suite

**Comment by TomaszMa** [comment]
@datamadic @whyn07m3 Agree with you guys, but do we have place where I could add these two constants, or there in no source file for this purpose, and I need to create it.

**Comment by whyn07m3** [comment]
@TomaszMa IMO, the "closest", but not the best, location where you could put these constants would be `src/shapes.ts`. Maybe if we have more of such constants throughout the project later on, we can create a separate file.

**Pull request merged**
