### PR TITLE
RUN-3596 if not subscribed to request errors, the net module will throw an exception.

### PR DESCRIPTION
**Pull request by rdepena**
@datamadic @StevenEBarbaro @wenjunche @whyn07m3 check it out.

### CODE REVIEW

**Comment by HarsimranSingh** [comment]
👍

**Comment by wenjunche** [comment]
probably need 
    response.once('error', ... )
as well

**Comment by rdepena** [comment]
@wenjunche updated.

**Comment by rdepena** [comment]
Test run
[Win7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5a0de56a9a4b9e06a97239f3)
[Win10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5a0de5e69a4b9e06a97239f4)

**Pull request merged**
